# Converts a vertical image to webp
[no-cd]
convertv file_path out_path:
    cwebp {{file_path}} -o {{out_path}} -resize 434 578 -q 100

# Converts a horisontal image to webp
[no-cd]
convertl file_path out_path:
    cwebp {{file_path}} -o {{out_path}} -resize 578 434 -q 100
